### ISSUE TITLE
Does not take effect after configuration

### ISSUE THREAD

**Issue by qianzai** [markbattistella/docsify-autoHeaders#2]
Follow your README and then he doesn't take effect.The control reported the following error
![image](https://user-images.githubusercontent.com/46664739/106690006-f077f980-660b-11eb-838d-f1b10969a679.png)

Where else do I need to configure it?

![image](https://user-images.githubusercontent.com/46664739/106690042-fec61580-660b-11eb-836d-d3bde0677a8d.png)

**Comment by markbattistella** [comment]
Have you added the `scope` in?

From the demo:
```
autoHeaders: {
  separator:	'decimal',
  levels:		'3',
  scope:		'#main' // <-------- this
}
```

This is the HTML id that it will contain the header numbering within

**Comment by qianzai** [comment]
> Have you added the `scope` in?
> 
> From the demo:
> 
> ```
> autoHeaders: {
>   separator:	'decimal',
>   levels:		'3',
>   scope:		'#main' // <-------- this
> }
> ```
> 
> This is the HTML id that it will contain the header numbering within

very thankful

**Comment by qianzai** [comment]
> Have you added the `scope` in?
> 
> From the demo:
> 
> ```
> autoHeaders: {
>   separator:	'decimal',
>   levels:		'3',
>   scope:		'#main' // <-------- this
> }
> ```
> 
> This is the HTML id that it will contain the header numbering within

very thankful！！

**Comment by markbattistella** [comment]
No worries! I'll push through a new update to default to `<main>` soon :)
