### ISSUE TITLE
Is it possible to number headers from the second level

### ISSUE THREAD

**Issue by fyemath** [markbattistella/docsify-autoHeaders#4]
Normally, we use H1 for the title of a page which we don't want it to be numbered. Is it possible the configure the numbering starting from H2 level?

Thank you!

**Comment by markbattistella** [comment]
Not currently possible but that's a very valid point! I'll look into it and see if it is possible. I'm thinking if you pop the numbering as `@autoheaders:-.5.6.6.1.12` or similar to skip the H1 then get it to operate on that. Or have something else that is doc by doc options

**Comment by markbattistella** [comment]
@fyemath please find the update to the script to help your situation. its not the best, but it works :)
